# Site settings
url    : "https://supreme-fiesta-5gvp476v79v3vrpg-4000.app.github.dev"
baseurl: "/"

title      : "Portfolio"
email      : contact@ounols.kr
description: "포트폴리오 사이트입니다."
author     : "Ounols"

collections:
  portfolio:
  sections:
    output: false

markdown: kramdown

plugins:
  - jekyll-feed
